import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Provider";
import { Toaster } from "react-hot-toast";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DailyTime24 Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${siliguri.className}`}>
        <Providers>
          {children}
        </Providers>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
