export const divisionOption = [
  { label: "ঢাকা", value: "Dhaka" },
  { label: "চট্টগ্রাম", value: "Chattogram" },
  { label: "খুলনা", value: "Khulna" },
  { label: "রাজশাহী", value: "Rajshahi" },
  { label: "বরিশাল", value: "Barishal" },
  { label: "রংপুর", value: "Rangpur" },
  { label: "সিলেট", value: "Sylhet" },
  { label: "ময়মনসিংহ", value: "Mymensingh" },
];
export const districtOption = [
  { label: "ঢাকা", value: "Dhaka" },
  { label: "গাজীপুর", value: "Gazipur" },
  { label: "মানিকগঞ্জ", value: "Manikganj" },
  { label: "মুন্সিগঞ্জ", value: "Munshiganj" },
  { label: "নারায়ণগঞ্জ", value: "Narayanganj" },
  { label: "নরসিংদী", value: "Narsingdi" },
  { label: "রাজবাড়ী", value: "Rajbari" },
  { label: "ফরিদপুর", value: "Faridpur" },
  { label: "মাদারীপুর", value: "Madaripur" },
  { label: "শরীয়তপুর", value: "Shariatpur" },
  { label: "গোপালগঞ্জ", value: "Gopalganj" },
  { label: "ব্রাহ্মণবাড়িয়া", value: "Brahmanbaria" },
  { label: "চাঁদপুর", value: "Chandpur" },
  { label: "কুমিল্লা", value: "Cumilla" },
  { label: "ফেনী", value: "Feni" },
  { label: "খাগড়াছড়ি", value: "Khagrachhari" },
  { label: "রাঙ্গামাটি", value: "Rangamati" },
  { label: "বান্দরবান", value: "Bandarban" },
  { label: "কক্সবাজার", value: "Cox's Bazar" },
  { label: "চট্টগ্রাম", value: "Chattogram" },
  { label: "বরিশাল", value: "Barishal" },
  { label: "ভোলা", value: "Bhola" },
  { label: "ঝালকাঠি", value: "Jhalokati" },
  { label: "পটুয়াখালী", value: "Patuakhali" },
  { label: "পিরোজপুর", value: "Pirojpur" },
  { label: "খুলনা", value: "Khulna" },
  { label: "বাগেরহাট", value: "Bagerhat" },
  { label: "চুয়াডাঙ্গা", value: "Chuadanga" },
  { label: "যশোর", value: "Jashore" },
  { label: "ঝিনাইদহ", value: "Jhenaidah" },
  { label: "কুষ্টিয়া", value: "Kushtia" },
  { label: "মাগুরা", value: "Magura" },
  { label: "মেহেরপুর", value: "Meherpur" },
  { label: "নড়াইল", value: "Narail" },
  { label: "সাতক্ষীরা", value: "Satkhira" },
  { label: "রাজশাহী", value: "Rajshahi" },
  { label: "চাঁপাইনবাবগঞ্জ", value: "Chapainawabganj" },
  { label: "নাটোর", value: "Natore" },
  { label: "নওগাঁ", value: "Naogaon" },
  { label: "পাবনা", value: "Pabna" },
  { label: "সিরাজগঞ্জ", value: "Sirajganj" },
  { label: "রংপুর", value: "Rangpur" },
  { label: "দিনাজপুর", value: "Dinajpur" },
  { label: "গাইবান্ধা", value: "Gaibandha" },
  { label: "কুড়িগ্রাম", value: "Kurigram" },
  { label: "লালমনিরহাট", value: "Lalmonirhat" },
  { label: "নীলফামারী", value: "Nilphamari" },
  { label: "পঞ্চগড়", value: "Panchagarh" },
  { label: "সিলেট", value: "Sylhet" },
  { label: "হবিগঞ্জ", value: "Habiganj" },
  { label: "মৌলভীবাজার", value: "Moulvibazar" },
  { label: "সুনামগঞ্জ", value: "Sunamganj" },
  { label: "ময়মনসিংহ", value: "Mymensingh" },
  { label: "শেরপুর", value: "Sherpur" },
  { label: "জামালপুর", value: "Jamalpur" },
  { label: "টাঙ্গাইল", value: "Tangail" },
];
export const upazilaOption = [

  // ঢাকা বিভাগের উপজেলাসমূহ
  { label: "কেরানীগঞ্জ", value: "Keraniganj" },
  { label: "দোহার", value: "Dohar" },
  { label: "ধামরাই", value: "Dhamrai" },
  { label: "নবাবগঞ্জ", value: "Nawabganj" },
  { label: "সাভার", value: "Savar" },
  { label: "গাজীপুর সদর", value: "Gazipur Sadar" },
  { label: "কালিয়াকৈর", value: "Kaliakair" },
  { label: "কাপাসিয়া", value: "Kapasia" },
  { label: "শ্রীপুর", value: "Sreepur" },
  { label: "মানিকগঞ্জ সদর", value: "Manikganj Sadar" },
  { label: "সিংগাইর", value: "Singair" },
  { label: "সাটুরিয়া", value: "Saturia" },
  { label: "শিবালয়", value: "Shibalaya" },
  { label: "হরিরামপুর", value: "Harirampur" },
  { label: "মুন্সিগঞ্জ সদর", value: "Munshiganj Sadar" },
  { label: "গজারিয়া", value: "Gazaria" },
  { label: "শ্রীনগর", value: "Sreenagar" },
  { label: "টঙ্গীবাড়ী", value: "Tongibari" },
  { label: "নারায়ণগঞ্জ সদর", value: "Narayanganj Sadar" },
  { label: "আড়াইহাজার", value: "Araihazar" },
  { label: "সোনারগাঁও", value: "Sonargaon" },
  { label: "রূপগঞ্জ", value: "Rupganj" },
  { label: "নরসিংদী সদর", value: "Narsingdi Sadar" },
  { label: "বেলাবো", value: "Belabo" },
  { label: "মনোহরদী", value: "Monohardi" },
  { label: "পলাশ", value: "Palash" },
  { label: "রায়পুরা", value: "Raipura" },
  { label: "রাজবাড়ী সদর", value: "Rajbari Sadar" },
  { label: "বালিয়াকান্দি", value: "Baliakandi" },
  { label: "পাংশা", value: "Pangsa" },
  { label: "গোয়ালন্দ", value: "Goalanda" },
  { label: "ফরিদপুর সদর", value: "Faridpur Sadar" },
  { label: "বোয়ালমারী", value: "Boalmari" },
  { label: "আলফাডাঙ্গা", value: "Alfadanga" },
  { label: "মধুখালী", value: "Madhukhali" },
  { label: "নগরকান্দা", value: "Nagarkanda" },
  { label: "সালথা", value: "Saltha" },
  { label: "ভাঙ্গা", value: "Bhanga" },
  { label: "চরভদ্রাসন", value: "Charbhadrasan" },
  { label: "সদরপুর", value: "Sadarpur" },
  { label: "মাদারীপুর সদর", value: "Madaripur Sadar" },
  { label: "কালকিনি", value: "Kalkini" },
  { label: "শিবচর", value: "Shibchar" },
  { label: "শরীয়তপুর সদর", value: "Shariatpur Sadar" },
  { label: "ডামুড্যা", value: "Damudya" },
  { label: "নড়িয়া", value: "Naria" },
  { label: "জাজিরা", value: "Jajira" },
  { label: "গোসাইরহাট", value: "Gosaighat" },
  { label: "গোপালগঞ্জ সদর", value: "Gopalganj Sadar" },
  { label: "কোটালীপাড়া", value: "Kotalipara" },
  { label: "টুঙ্গিপাড়া", value: "Tungipara" },
  //চট্টগ্রাম বিভাগ
  { label: "চট্টগ্রাম সদর", value: "Chattogram Sadar" },
  { label: "আনোয়ারা", value: "Anwara" },
  { label: "বাঁশখালী", value: "Banshkhali" },
  { label: "বোয়ালখালী", value: "Boalkhali" },
  { label: "চন্দনাইশ", value: "Chandanaish" },
  { label: "ফটিকছড়ি", value: "Fatikchhari" },
  { label: "হাটহাজারী", value: "Hathazari" },
  { label: "লোহাগাড়া", value: "Lohagara" },
  { label: "মীরসরাই", value: "Mirsharai" },
  { label: "পটিয়া", value: "Patiya" },
  { label: "রাউজান", value: "Raozan" },
  { label: "সন্দ্বীপ", value: "Sandwip" },
  { label: "সাতকানিয়া", value: "Satkania" },
  { label: "সীতাকুণ্ড", value: "Sitakunda" },
  { label: "কর্ণফুলী", value: "Karnaphuli" },
  { label: "কক্সবাজার সদর", value: "Cox's Bazar Sadar" },
  { label: "চকরিয়া", value: "Chakaria" },
  { label: "কুতুবদিয়া", value: "Kutubdia" },
  { label: "মহেশখালী", value: "Maheshkhali" },
  { label: "রামু", value: "Ramu" },
  { label: "টেকনাফ", value: "Teknaf" },
  { label: "উখিয়া", value: "Ukhiya" },
  { label: "পেকুয়া", value: "Pekua" },
  { label: "বান্দরবান সদর", value: "Bandarban Sadar" },
  { label: "আলিকদম", value: "Alikadam" },
  { label: "থানচি", value: "Thanchi" },
  { label: "নাইক্ষ্যংছড়ি", value: "Naikhongchhari" },
  { label: "রুমা", value: "Ruma" },
  { label: "রোয়াংছড়ি", value: "Rowangchhari" },
  { label: "লামা", value: "Lama" },
  { label: "খাগড়াছড়ি সদর", value: "Khagrachhari Sadar" },
  { label: "দীঘিনালা", value: "Dighinala" },
  { label: "পানছড়ি", value: "Panchhari" },
  { label: "লক্ষীছড়ি", value: "Lakshmichhari" },
  { label: "মহালছড়ি", value: "Mohalchhari" },
  { label: "মানিকছড়ি", value: "Manikchhari" },
  { label: "রামগড়", value: "Ramgarh" },
  { label: "মাটিরাঙ্গা", value: "Matiranga" },
  { label: "রাঙ্গামাটি সদর", value: "Rangamati Sadar" },
  { label: "কাপ্তাই", value: "Kaptai" },
  { label: "বাঘাইছড়ি", value: "Bagaichhari" },
  { label: "জুরাছড়ি", value: "Juraichhari" },
  { label: "বরকল", value: "Barkal" },
  { label: "লংগদু", value: "Langadu" },
  { label: "রাজস্থলী", value: "Rajasthali" },
  { label: "বিলাইছড়ি", value: "Bilaichhari" },
  { label: "নানিয়ারচর", value: "Naniarchar" },
  { label: "ব্রাহ্মণবাড়িয়া সদর", value: "Brahmanbaria Sadar" },
  { label: "কসবা", value: "Kasba" },
  { label: "আখাউড়া", value: "Akhaura" },
  { label: "সরাইল", value: "Sarail" },
  { label: "নাসিরনগর", value: "Nasirnagar" },
  { label: "বাঞ্ছারামপুর", value: "Bancharampur" },
  { label: "নবীনগর", value: "Nabinagar" },
  { label: "বিজয়নগর", value: "Bijoynagar" },
  { label: "চাঁদপুর সদর", value: "Chandpur Sadar" },
  { label: "ফরিদগঞ্জ", value: "Faridganj" },
  { label: "কচুয়া", value: "Kachua" },
  { label: "মতলব উত্তর", value: "Matlab Uttar" },
  { label: "মতলব দক্ষিণ", value: "Matlab Dakshin" },
  { label: "শাহরাস্তি", value: "Shahrasti" },
  { label: "হাজীগঞ্জ", value: "Hajiganj" },
  { label: "কুমিল্লা সদর", value: "Cumilla Sadar" },
  { label: "বরুড়া", value: "Barura" },
  { label: "ব্রাহ্মণপাড়া", value: "Brahmanpara" },
  { label: "চান্দিনা", value: "Chandina" },
  { label: "চৌদ্দগ্রাম", value: "Chauddagram" },
  { label: "দাউদকান্দি", value: "Daudkandi" },
  { label: "দেবিদ্বার", value: "Debidwar" },
  { label: "হোমনা", value: "Homna" },
  { label: "লাকসাম", value: "Laksam" },
  { label: "মুরাদনগর", value: "Muradnagar" },
  { label: "নাঙ্গলকোট", value: "Nangalkot" },
  { label: "মেঘনা", value: "Meghna" },
  { label: "তিতাস", value: "Titas" },
  { label: "মনোহরগঞ্জ", value: "Monohorgonj" },
  { label: "সদর দক্ষিণ", value: "Sadar Dakshin" },
  { label: "লালমাই", value: "Lalmai" },
  { label: "ফেনী সদর", value: "Feni Sadar" },
  { label: "ছাগলনাইয়া", value: "Chhagalnaiya" },
  { label: "দাগনভূঞা", value: "Daganbhuiyan" },
  { label: "সোনাগাজী", value: "Sonagazi" },
  { label: "পরশুরাম", value: "Parshuram" },
  { label: "ফুলগাজী", value: "Fulgazi" },
  // বরিশাল
  { label: "বরিশাল সদর", value: "Barishal Sadar" },
  { label: "আগৈলঝাড়া", value: "Agailjhara" },
  { label: "বাবুগঞ্জ", value: "Babuganj" },
  { label: "বাকেরগঞ্জ", value: "Bakerganj" },
  { label: "বানারীপাড়া", value: "Banaripara" },
  { label: "গৌরনদী", value: "Gournadi" },
  { label: "হিজলা", value: "Hijla" },
  { label: "মেহেন্দিগঞ্জ", value: "Mehendiganj" },
  { label: "মুলাদী", value: "Muladi" },
  { label: "উজিরপুর", value: "Wazirpur" },
  { label: "ভোলা সদর", value: "Bhola Sadar" },
  { label: "বোরহানউদ্দিন", value: "Borhanuddin" },
  { label: "চরফ্যাশন", value: "Char Fasson" },
  { label: "দৌলতখান", value: "Daulatkhan" },
  { label: "লালমোহন", value: "Lalmohan" },
  { label: "মনপুরা", value: "Monpura" },
  { label: "তজুমদ্দিন", value: "Tazumuddin" },
  { label: "ঝালকাঠি সদর", value: "Jhalokati Sadar" },
  { label: "কাউখালী", value: "Kaukhali" },
  { label: "নলছিটি", value: "Nalchity" },
  { label: "রাজাপুর", value: "Rajapur" },
  { label: "পটুয়াখালী সদর", value: "Patuakhali Sadar" },
  { label: "বাউফল", value: "Bauphal" },
  { label: "দশমিনা", value: "Dashmina" },
  { label: "কলাপাড়া", value: "Kalapara" },
  { label: "মির্জাগঞ্জ", value: "Mirzaganj" },
  { label: "রাঙ্গাবালী", value: "Rangabali" },
  { label: "দুমকি", value: "Dumki" },
  { label: "পিরোজপুর সদর", value: "Pirojpur Sadar" },
  { label: "ভাণ্ডারিয়া", value: "Bhandaria" },
  { label: "কাউখালী (পিরোজপুর)", value: "Kaukhali (Pirojpur)" },
  { label: "নেছারাবাদ (স্বরূপকাঠি)", value: "Nesharabad (Swarupkati)" },
  { label: "নাজিরপুর", value: "Nazirpur" },
  { label: "মঠবাড়িয়া", value: "Mathbaria" },
  { label: "ইন্দুরকানী", value: "Indurkani" },
  { label: "পাথরঘাটা", value: "Patharghata" },
  { label: "বেতাগী", value: "Betagi" },
  { label: "আমতলী", value: "Amtali" },
  // খুলনা
  { label: "খুলনা সদর", value: "Khulna Sadar" },
  { label: "বটিয়াঘাটা", value: "Batiaghata" },
  { label: "দাকোপ", value: "Dacope" },
  { label: "ডুমুরিয়া", value: "Dumuria" },
  { label: "দিঘলিয়া", value: "Dighalia" },
  { label: "কয়রা", value: "Koyra" },
  { label: "পাইকগাছা", value: "Paikgacha" },
  { label: "ফুলতলা", value: "Phultala" },
  { label: "রূপসা", value: "Rupsa" },
  { label: "তেরখাদা", value: "Terokhada" },
  { label: "বাগেরহাট সদর", value: "Bagerhat Sadar" },
  { label: "চিতলমারী", value: "Chitalmari" },
  { label: "ফকিরহাট", value: "Fakirhat" },
  { label: "কচুয়া", value: "Kachua (Bagerhat)" },
  { label: "মোল্লাহাট", value: "Mollahat" },
  { label: "মোংলা", value: "Mongla" },
  { label: "মোড়েলগঞ্জ", value: "Morrelganj" },
  { label: "রামপাল", value: "Rampal" },
  { label: "শরণখোলা", value: "Sharankhola" },
  { label: "চুয়াডাঙ্গা সদর", value: "Chuadanga Sadar" },
  { label: "আলমডাঙ্গা", value: "Alamdanga" },
  { label: "দামুড়হুদা", value: "Damurhuda" },
  { label: "জীবননগর", value: "Jibannagar" },
  { label: "যশোর সদর", value: "Jashore Sadar" },
  { label: "অভয়নগর", value: "Abhaynagar" },
  { label: "বাঘারপাড়া", value: "Bagharpara" },
  { label: "চৌগাছা", value: "Chaugachha" },
  { label: "ঝিকরগাছা", value: "Jhikargacha" },
  { label: "কেশবপুর", value: "Keshabpur" },
  { label: "মনিরামপুর", value: "Manirampur" },
  { label: "শার্শা", value: "Sharsha" },
  { label: "ঝিনাইদহ সদর", value: "Jhenaidah Sadar" },
  { label: "কালীগঞ্জ", value: "Kaliganj (Jhenaidah)" },
  { label: "কোটচাঁদপুর", value: "Kotchandpur" },
  { label: "মহেশপুর", value: "Maheshpur" },
  { label: "শৈলকুপা", value: "Shailkupa" },
  { label: "হরিনাকুণ্ডু", value: "Harinakundu" },
  { label: "কুষ্টিয়া সদর", value: "Kushtia Sadar" },
  { label: "ভেড়ামারা", value: "Bheramara" },
  { label: "দৌলতপুর", value: "Daulatpur (Kushtia)" },
  { label: "খোকসা", value: "Khoksa" },
  { label: "কুমারখালী", value: "Kumarkhali" },
  { label: "মিরপুর", value: "Mirpur (Kushtia)" },
  { label: "মাগুরা সদর", value: "Magura Sadar" },
  { label: "মহম্মদপুর", value: "Mohammadpur (Magura)" },
  { label: "শালিখা", value: "Shalikha" },
  { label: "শ্রীপুর", value: "Sreepur (Magura)" },
  { label: "মেহেরপুর সদর", value: "Meherpur Sadar" },
  { label: "গাংনী", value: "Gangni" },
  { label: "মুজিবনগর", value: "Mujibnagar" },
  { label: "নড়াইল সদর", value: "Narail Sadar" },
  { label: "কালিয়া", value: "Kalia" },
  { label: "লোহাগড়া", value: "Lohagara (Narail)" },
  { label: "সাতক্ষীরা সদর", value: "Satkhira Sadar" },
  { label: "আশাশুনি", value: "Assasuni" },
  { label: "দেবহাটা", value: "Debhata" },
  { label: "কালীগঞ্জ", value: "Kaliganj (Satkhira)" },
  { label: "শ্যামনগর", value: "Shyamnagar" },
  { label: "তালা", value: "Tala" },
  { label: "কলারোয়া", value: "Kalaroa" },
  // রাজশাহী
  { label: "রাজশাহী সদর", value: "Rajshahi Sadar" },
  { label: "বাঘা", value: "Bagha" },
  { label: "বাগমারা", value: "Bagmara" },
  { label: "চারঘাট", value: "Charghat" },
  { label: "দুর্গাপুর", value: "Durgapur" },
  { label: "গোদাগাড়ী", value: "Godagari" },
  { label: "মোহনপুর", value: "Mohanpur" },
  { label: "পবা", value: "Paba" },
  { label: "পুঠিয়া", value: "Puthia" },
  { label: "তানোর", value: "Tanore" },
  { label: "চাঁপাইনবাবগঞ্জ সদর", value: "Chapainawabganj Sadar" },
  { label: "ভোলাহাট", value: "Bholahat" },
  { label: "গোমস্তাপুর", value: "Gomostapur" },
  { label: "নাচোল", value: "Nachole" },
  { label: "শিবগঞ্জ", value: "Shibganj (Chapainawabganj)" },
  { label: "নাটোর সদর", value: "Natore Sadar" },
  { label: "বাগাতিপাড়া", value: "Bagatipara" },
  { label: "গুরুদাসপুর", value: "Gurudaspur" },
  { label: "লালপুর", value: "Lalpur" },
  { label: "সিংড়া", value: "Singra" },
  { label: "নওগাঁ সদর", value: "Naogaon Sadar" },
  { label: "আত্রাই", value: "Atrai" },
  { label: "বদলগাছী", value: "Badalgachhi" },
  { label: "ধামইরহাট", value: "Dhamoirhat" },
  { label: "মহাদেবপুর", value: "Mahadevpur" },
  { label: "মান্দা", value: "Manda" },
  { label: "নিয়ামতপুর", value: "Niamatpur" },
  { label: "পত্নীতলা", value: "Patnitala" },
  { label: "পোরশা", value: "Porsha" },
  { label: "রাণীনগর", value: "Raninagar" },
  { label: "সাপাহার", value: "Sapahar" },
  { label: "পাবনা সদর", value: "Pabna Sadar" },
  { label: "আটঘরিয়া", value: "Atgharia" },
  { label: "বেড়া", value: "Bera" },
  { label: "ভাঙ্গুড়া", value: "Bhangura" },
  { label: "চাটমোহর", value: "Chatmohar" },
  { label: "ফরিদপুর", value: "Faridpur (Pabna)" },
  { label: "ঈশ্বরদী", value: "Ishwardi" },
  { label: "সাঁথিয়া", value: "Santhia" },
  { label: "সুজানগর", value: "Sujanagar" },
  { label: "সিরাজগঞ্জ সদর", value: "Sirajganj Sadar" },
  { label: "বেলকুচি", value: "Belkuchi" },
  { label: "চৌহালী", value: "Chauhali" },
  { label: "কামারখন্দ", value: "Kamarkhanda" },
  { label: "কাজীপুর", value: "Kazipur" },
  { label: "রায়গঞ্জ", value: "Raiganj (Sirajganj)" },
  { label: "শাহজাদপুর", value: "Shahjadpur" },
  { label: "সলঙ্গা", value: "Salanga" },
  { label: "তাড়াশ", value: "Tarash" },
  { label: "উল্লাপাড়া", value: "Ullahpara" },
  // রংপুর
  { label: "রংপুর সদর", value: "Rangpur Sadar" },
  { label: "বদরগঞ্জ", value: "Badarganj" },
  { label: "গঙ্গাচড়া", value: "Gangachara" },
  { label: "কাউনিয়া", value: "Kaunia" },
  { label: "পীরগাছা", value: "Pirgachha" },
  { label: "পীরগঞ্জ", value: "Pirganj (Rangpur)" },
  { label: "তারাগঞ্জ", value: "Taraganj" },
  { label: "মিঠাপুকুর", value: "Mithapukur" },
  { label: "দিনাজপুর সদর", value: "Dinajpur Sadar" },
  { label: "বিরল", value: "Biral" },
  { label: "বোচাগঞ্জ", value: "Bochaganj" },
  { label: "চিরিরবন্দর", value: "Chirirbandar" },
  { label: "ফুলবাড়ী", value: "Phulbari (Dinajpur)" },
  { label: "ঘোড়াঘাট", value: "Ghoraghat" },
  { label: "হাকিমপুর", value: "Hakimpur" },
  { label: "কাহারোল", value: "Kaharole" },
  { label: "খানসামা", value: "Khansama" },
  { label: "নবাবগঞ্জ", value: "Nawabganj (Dinajpur)" },
  { label: "পার্বতীপুর", value: "Parbatipur" },
  { label: "গাইবান্ধা সদর", value: "Gaibandha Sadar" },
  { label: "ফুলছড়ি", value: "Phulchhari" },
  { label: "গোবিন্দগঞ্জ", value: "Gobindaganj" },
  { label: "পলাশবাড়ী", value: "Palashbari" },
  { label: "সাদুল্লাপুর", value: "Sadullapur" },
  { label: "সাঘাটা", value: "Saghata" },
  { label: "সুন্দরগঞ্জ", value: "Sundarganj" },
  { label: "কুড়িগ্রাম সদর", value: "Kurigram Sadar" },
  { label: "ভূরুঙ্গামারী", value: "Bhurungamari" },
  { label: "চর রাজীবপুর", value: "Char Rajibpur" },
  { label: "চিলমারী", value: "Chilmari" },
  { label: "ফুলবাড়ী", value: "Phulbari (Kurigram)" },
  { label: "উলিপুর", value: "Ulipur" },
  { label: "রাজারহাট", value: "Rajarhat" },
  { label: "রৌমারী", value: "Raomari" },
  { label: "নাগেশ্বরী", value: "Nageshwari" },
  { label: "লালমনিরহাট সদর", value: "Lalmonirhat Sadar" },
  { label: "আদিতমারী", value: "Aditmari" },
  { label: "কালীগঞ্জ", value: "Kaliganj (Lalmonirhat)" },
  { label: "হাতীবান্ধা", value: "Hatibandha" },
  { label: "পাটগ্রাম", value: "Patgram" },
  { label: "নীলফামারী সদর", value: "Nilphamari Sadar" },
  { label: "ডোমকল", value: "Domar" },
  { label: "ডিমলা", value: "Dimla" },
  { label: "জলঢাকা", value: "Jaldhaka" },
  { label: "কিশোরগঞ্জ", value: "Kishoreganj (Nilphamari)" },
  { label: "সৈয়দপুর", value: "Saidpur" },
  { label: "পঞ্চগড় সদর", value: "Panchagarh Sadar" },
  { label: "আটোয়ারী", value: "Atwari" },
  { label: "বোদা", value: "Boda" },
  { label: "দেবীগঞ্জ", value: "Debiganj" },
  { label: "তেঁতুলিয়া", value: "Tetulia" },
  // সিলেট
  { label: "সিলেট সদর", value: "Sylhet Sadar" },
  { label: "বালাগঞ্জ", value: "Balaganj" },
  { label: "বিয়ানীবাজার", value: "Beanibazar" },
  { label: "বিশ্বনাথ", value: "Bishwanath" },
  { label: "কোম্পানীগঞ্জ", value: "Companiganj" },
  { label: "ফেঞ্চুগঞ্জ", value: "Fenchuganj" },
  { label: "গোলাপগঞ্জ", value: "Golapganj" },
  { label: "জকিগঞ্জ", value: "Zakiganj" },
  { label: "কানাইঘাট", value: "Kanaighat" },
  { label: "দক্ষিণ সুরমা", value: "Dakshin Surma" },
  { label: "গোয়াইনঘাট", value: "Gowainghat" },
  { label: "জৈন্তাপুর", value: "Jaintiapur" },
  { label: "হবিগঞ্জ সদর", value: "Habiganj Sadar" },
  { label: "আজমিরীগঞ্জ", value: "Ajmiriganj" },
  { label: "বাহুবল", value: "Bahubal" },
  { label: "বানিয়াচং", value: "Baniachong" },
  { label: "চুনারুঘাট", value: "Chunarughat" },
  { label: "মাধবপুর", value: "Madhabpur" },
  { label: "নবীগঞ্জ", value: "Nabiganj" },
  { label: "লাখাই", value: "Lakhai" },
  { label: "মৌলভীবাজার সদর", value: "Moulvibazar Sadar" },
  { label: "বড়লেখা", value: "Barlekha" },
  { label: "জুড়ী", value: "Juri" },
  { label: "কমলগঞ্জ", value: "Kamalganj" },
  { label: "কুলাউড়া", value: "Kulaura" },
  { label: "রাজনগর", value: "Rajnagar" },
  { label: "শ্রীমঙ্গল", value: "Sreemangal" },
  { label: "সুনামগঞ্জ সদর", value: "Sunamganj Sadar" },
  { label: "দিরাই", value: "Dirai" },
  { label: "দোয়ারাবাজার", value: "Dowarabazar" },
  { label: "জগন্নাথপুর", value: "Jagannathpur" },
  { label: "দক্ষিণ সুনামগঞ্জ", value: "Dakshin Sunamganj" },
  { label: "জামালগঞ্জ", value: "Jamalganj" },
  { label: "শাল্লা", value: "Shalla" },
  { label: "তাহিরপুর", value: "Tahirpur" },
  { label: "ছাতক", value: "Chhatak" },
  { label: "মধ্যনগর", value: "Madhyanagar" },
  // ময়মনসিংহ
  { label: "ময়মনসিংহ সদর", value: "Mymensingh Sadar" },
  { label: "ভালুকা", value: "Bhaluka" },
  { label: "ত্রিশাল", value: "Trishal" },
  { label: "গফরগাঁও", value: "Gaffargaon" },
  { label: "ঈশ্বরগঞ্জ", value: "Ishwarganj" },
  { label: "মুক্তাগাছা", value: "Muktagacha" },
  { label: "নান্দাইল", value: "Nandail" },
  { label: "ফুলবাড়ীয়া", value: "Phulbaria (Mymensingh)" },
  { label: "গৌরীপুর", value: "Gauripur" },
  { label: "হালুয়াঘাট", value: "Haluaghat" },
  { label: "ধোবাউড়া", value: "Dobaura" },
  { label: "ফুলপুর", value: "Fulpur" },
  { label: "নালিতাবাড়ী", value: "Nalitabari" },
  { label: "শ্রীবরদী", value: "Sreebardi" },
  { label: "ঝিনাইগাতী", value: "Jhenaigati" },
  { label: "শেরপুর সদর", value: "Sherpur Sadar" },
  { label: "নকলা", value: "Nakla" },
  { label: "সরিষাবাড়ী", value: "Sarishabari" },
  { label: "জামালপুর সদর", value: "Jamalpur Sadar" },
  { label: "বক্সীগঞ্জ", value: "Baksiganj" },
  { label: "দেওয়ানগঞ্জ", value: "Dewanganj" },
  { label: "ইসলামপুর", value: "Islampur (Jamalpur)" },
  { label: "মাদারগঞ্জ", value: "Madarganj" },
  { label: "মেলান্দহ", value: "Melandaha" },
  { label: "টাঙ্গাইল সদর", value: "Tangail Sadar" },
  { label: "বাসাইল", value: "Basail" },
  { label: "ভূয়াপুর", value: "Bhuapur" },
  { label: "দেলদুয়ার", value: "Delduar" },
  { label: "ঘাটাইল", value: "Ghatail" },
  { label: "কালিহাতী", value: "Kalihati" },
  { label: "মধুপুর", value: "Madhupur" },
  { label: "মির্জাপুর", value: "Mirzapur (Tangail)" },
  { label: "নাগরপুর", value: "Nagarpur" },
  { label: "সখিপুর", value: "Sakhipur" },
  { label: "ধনবাড়ী", value: "Dhanbari" },

];
export const newsTagOption = [
  { label: "সর্বশেষ", value: "latest" },
  { label: "গুরুত্বপূর্ণ", value: "important" },
  { label: "দৈনিক ইসলাম", value: "daily-islam" },
  { label: "খেলাধুলা", value: "sports" },
  { label: "আন্তর্জাতিক", value: "international" },
  { label: "শিক্ষা", value: "education" },
  { label: "সাক্ষাৎকার", value: "meeting" },
  { label: "মতামত", value: "opinion" },
  { label: "ফিচার", value: "feature" },
  { label: "সম্ভার", value: "sombar" },
  { label: "সবচেয়ে পঠিত", value: "most-readable" },
  { label: "আলোচিত", value: "discussed" },
  { label: "সুখবর", value: "good-news" },
  { label: "চাকরি", value: "job" },
];
export const reporterTypeOption = [
  {
    label: "নিজস্ব প্রতিনিধি",
    value: "own_representative",
  },
  { label: "প্রতিনিধি", value: "representative" },
  {
    label: "বিশেষ প্রতিনিধি",
    value: "special_representative",
  },
  { label: "স্টাফ রিপোর্টার", value: "staff_reporter" },
  {
    label: "আঞ্চলিক প্রতিনিধি",
    value: "regional_representative",
  },
  {
    label: "জেলা প্রতিনিধি",
    value: "district_representative",
  },
  {
    label: "উপজেলা প্রতিনিধি",
    value: "subdistrict_representative",
  },
  {
    label: "সাংস্কৃতিক প্রতিনিধি",
    value: "cultural_representative",
  },
  {
    label: "খেলাধুলা প্রতিনিধি",
    value: "sports_representative",
  },
  {
    label: "অর্থনৈতিক প্রতিনিধি",
    value: "economic_representative",
  },
  {
    label: "রাজনৈতিক প্রতিনিধি",
    value: "political_representative",
  },
  {
    label: "সাহিত্য প্রতিনিধি",
    value: "literature_representative",
  },
  { label: "ক্রাইম রিপোর্টার", value: "crime_reporter" },
  {
    label: "স্বাস্থ্য প্রতিনিধি",
    value: "health_representative",
  },
  {
    label: "প্রবাস প্রতিনিধি",
    value: "expatriate_representative",
  },
  {
    label: "তথ্যপ্রযুক্তি প্রতিনিধি",
    value: "technology_representative",
  },
  {
    label: "পর্যটন প্রতিনিধি",
    value: "tourism_representative",
  },
]
